/*
 * TGui.java
 *
 * Created on __DATE__, __TIME__
 */


/**
 *
 * @author  __USER__
 */
public class Gui extends javax.swing.JFrame {

	Tomasulo t;
	
	/** Creates new form TGui */
	public Gui() {
		t = new Tomasulo();
		initComponents();
	}

	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JScrollPane jScrollPane5;
	private javax.swing.JTable jTable1;
	private javax.swing.JTable jTable2;
	private javax.swing.JTable jTable3;
	private javax.swing.JTable jTable4;
	private javax.swing.JTable jTable5;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jTextField5 = new javax.swing.JTextField();
		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTable2 = new javax.swing.JTable();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTable3 = new javax.swing.JTable();
		jTextField1 = new javax.swing.JTextField();
		jButton4 = new javax.swing.JButton();
		jTextField2 = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jButton5 = new javax.swing.JButton();
		jTextField3 = new javax.swing.JTextField();
		jTextField4 = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jTextField6 = new javax.swing.JTextField();
		jButton6 = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jScrollPane4 = new javax.swing.JScrollPane();
		jTable4 = new javax.swing.JTable();
		jScrollPane5 = new javax.swing.JScrollPane();
		jTable5 = new javax.swing.JTable();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();

		jTextField5.setText("jTextField5");

		setDefaultCloseOperation(3);

		jButton1.setText("载入文件");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("全部执行");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setText("单步执行");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jLabel8.setText("clock =");

		jLabel9.setText("jLabel9");

		jLabel10.setText("pc =");

		jLabel11.setText("jLabel11");

		org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel2Layout
										.createSequentialGroup()
										.add(jButton1)
										.add(27, 27, 27)
										.add(jButton2)
										.add(34, 34, 34)
										.add(jButton3)
										.add(48, 48, 48)
										.add(jLabel8)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(jLabel9)
										.add(47, 47, 47)
										.add(jLabel10)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(jLabel11).addContainerGap(189,
												Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel2Layout.createParallelGroup(
						org.jdesktop.layout.GroupLayout.BASELINE).add(jButton1)
						.add(jButton3).add(jButton2).add(jLabel8).add(jLabel9)
						.add(jLabel10).add(jLabel11)));

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },{ null, null, null, null },{ null, null, null, null },{ null, null, null, null },{ null, null, null, null },{ null, null, null, null },{ null, null, null, null },{ null, null, null, null },
						}, new String[] { "Inst Name", "Issue", "Exec Comp", "WB" }));
		jScrollPane1.setViewportView(jTable1);

		jTable2.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { 
						{ "F0", null, null, null },{ "F1", null, null, null },{ "F2", null, null, null },{ "F3", null, null, null },{ "F4", null, null, null },{ "F5", null, null, null },{ "F6", null, null, null },{ "F7", null, null, null },
				}, new String[] { "Reg",
						"Data", "Busy", "station"}));
		jScrollPane2.setViewportView(jTable2);

		jTable3.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { 
						{ null, null },	{ null, null },	{ null, null },	{ null, null },	{ null, null },	{ null, null },	{ null, null },	{ null, null },			
				}, new String[] { "Addr",
						"Data"}));
		jScrollPane3.setViewportView(jTable3);

		jTextField1.setText("Instruction");
		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});

		jButton4.setText("输入指令");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jTextField2.setText("Reg");
		jTextField2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField2ActionPerformed(evt);
			}
		});

		jLabel1.setText("=");

		jButton5.setText("修改Reg");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jTextField3.setText("Value");
		jTextField3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField3ActionPerformed(evt);
			}
		});

		jTextField4.setText("Addr");
		jTextField4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField4ActionPerformed(evt);
			}
		});

		jLabel2.setText("=");

		jTextField6.setText("Value");
		jTextField6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField6ActionPerformed(evt);
			}
		});

		jButton6.setText("修改内存");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});

		jLabel3.setText("\u6307\u4ee4\u961f\u5217");

		jLabel4.setText("\u5bc4\u5b58\u5668");

		jLabel5.setText("\u5185\u5b58");

		jTable4.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { "Load1", null, null, null },
						{ "Load2", null, null, null }, { "Load3", null, null, null },{ "Store1", null, null, null },{ "Store2", null, null, null },
						{ "Store3", null, null, null } }, new String[] { "",
						"Busy", "Addr", "Station" }));
		jScrollPane4.setViewportView(jTable4);

		jTable5.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { 
						{ "Add1", null, null, null, null, null, null }, { "Add2", null, null, null, null, null, null },{ "Add3", null, null, null, null, null, null },{ "Mul1", null, null, null, null, null, null },{ "Mul2", null, null, null, null, null, null }
						}, new String[] { "",
						"Busy", "Op", "Data1", "Station1", "Data2", "Station1",}));
		jScrollPane5.setViewportView(jTable5);

		jLabel6.setText("Load/Store Queue");

		jLabel7.setText("Reservation Station");

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel1Layout
										.createSequentialGroup()
										.add(161, 161, 161)
										.add(jLabel3)
										.add(232, 232, 232)
										.add(jLabel4)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED,
												213, Short.MAX_VALUE).add(
												jLabel5).add(70, 70, 70))
						.add(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																jPanel1Layout
																		.createSequentialGroup()
																		.add(
																				jScrollPane4,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				249,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				jScrollPane5,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				509,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addContainerGap())
														.add(
																jPanel1Layout
																		.createSequentialGroup()
																		.add(
																				70,
																				70,
																				70)
																		.add(
																				jLabel6)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED,
																				269,
																				Short.MAX_VALUE)
																		.add(
																				jLabel7)
																		.add(
																				225,
																				225,
																				225))))
						.add(
								jPanel1Layout
										.createSequentialGroup()
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																jPanel1Layout
																		.createSequentialGroup()
																		.add(
																				10,
																				10,
																				10)
																		.add(
																				jPanel1Layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.LEADING)
																						.add(
																								jPanel2,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.add(
																								jPanel1Layout
																										.createSequentialGroup()
																										.add(
																												jPanel1Layout
																														.createParallelGroup(
																																org.jdesktop.layout.GroupLayout.TRAILING)
																														.add(
																																jButton4)
																														.add(
																																jScrollPane1,
																																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																																318,
																																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																										.addPreferredGap(
																												org.jdesktop.layout.LayoutStyle.UNRELATED)
																										.add(
																												jPanel1Layout
																														.createParallelGroup(
																																org.jdesktop.layout.GroupLayout.LEADING)
																														.add(
																																jPanel1Layout
																																		.createSequentialGroup()
																																		.add(
																																				jTextField2,
																																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																																				59,
																																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				org.jdesktop.layout.LayoutStyle.RELATED)
																																		.add(
																																				jLabel1)
																																		.addPreferredGap(
																																				org.jdesktop.layout.LayoutStyle.RELATED)
																																		.add(
																																				jTextField3,
																																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																																				91,
																																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				org.jdesktop.layout.LayoutStyle.RELATED)
																																		.add(
																																				jButton5))
																														.add(
																																jScrollPane2,
																																0,
																																0,
																																Short.MAX_VALUE))
																										.add(
																												18,
																												18,
																												18)
																										.add(
																												jPanel1Layout
																														.createParallelGroup(
																																org.jdesktop.layout.GroupLayout.LEADING,
																																false)
																														.add(
																																jPanel1Layout
																																		.createSequentialGroup()
																																		.add(
																																				jTextField4,
																																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																																				38,
																																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				org.jdesktop.layout.LayoutStyle.RELATED)
																																		.add(
																																				jLabel2)
																																		.addPreferredGap(
																																				org.jdesktop.layout.LayoutStyle.RELATED)
																																		.add(
																																				jTextField6,
																																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																																				58,
																																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				org.jdesktop.layout.LayoutStyle.RELATED)
																																		.add(
																																				jButton6,
																																				10,
																																				10,
																																				Short.MAX_VALUE))
																														.add(
																																jScrollPane3,
																																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																																155,
																																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																										.addPreferredGap(
																												org.jdesktop.layout.LayoutStyle.RELATED,
																												4,
																												Short.MAX_VALUE))))
														.add(
																jPanel1Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.add(
																				jTextField1,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				230,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
										.add(18, 18, 18)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												jPanel2,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(21, 21, 21)
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jLabel3).add(
																jLabel4).add(
																jLabel5))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING,
																false)
														.add(jScrollPane3, 0,
																0,
																Short.MAX_VALUE)
														.add(jScrollPane2, 0,
																0,
																Short.MAX_VALUE)
														.add(
																jScrollPane1,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																221,
																Short.MAX_VALUE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jButton4)
														.add(
																jTextField1,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(
																jTextField2,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(jLabel1)
														.add(
																jTextField3,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(jButton5)
														.add(
																jTextField4,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(jLabel2)
														.add(
																jTextField6,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(jButton6))
										.add(18, 18, 18)
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jLabel6).add(
																jLabel7))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING,
																false)
														.add(jScrollPane5, 0,
																0,
																Short.MAX_VALUE)
														.add(
																jScrollPane4,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																152,
																Short.MAX_VALUE))
										.addContainerGap()));

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jPanel1,
				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				org.jdesktop.layout.GroupLayout.TRAILING, jPanel1,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Gui().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:vari

	// Variables declaration - do not m
	// End of variables declaration//GEN-END:variables

}